[package]
name = "ragenix"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
age = { version = "0.11.1", features = ["armor", "plugin", "ssh"] }
anyhow = "1.0.95"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.7"
pkg-config = "0.3.31"
